name: mac

on:
  push:
  pull_request:

jobs:
  run-tests:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        haxe:
          - 4.2.5
    with:
      runner-os: ${{ matrix.os }}
      haxe-version: ${{ matrix.haxe }}
      haxe-libs: |
        utest
      test-cpp:  tests/common.hxml --class-path tests

      before-tests: |
        git clone https://github.com/core-haxe/promises
        haxelib dev promises promises
        git clone https://github.com/core-haxe/logging
        haxelib dev logging logging
        git clone https://github.com/core-haxe/libsqlite3
        haxelib dev libsqlite3 libsqlite3
